### ISSUE TITLE
White Screen

### ISSUE THREAD

**Issue by ak0815** [DennisAhaus/mean.io-test-carsharing#1]
Hello,

I try to launch the app but there is always win White screen. Why is that?

grunt -f
Running "clean:0" (clean) task

Running "jshint:all" (jshint) task

   packages/cars/app.js
     30 |    roles: ["admin"],
                            ^ Strings must use singlequote.
   packages/cars/public/controllers/cars.js
     12 |    }
              ^ Missing semicolon.
     16 |    }
              ^ Missing semicolon.
     20 |    }
              ^ Missing semicolon.
     78 |    $scope.$watch("toogleBookedCars", function (newVal, oldVal) {
                                             ^ Strings must use singlequote.
     79 |      console.log("newVal:" + newVal + ";  old: "+ oldVal + "val: " + $scope.toogleBookedCars);
                                    ^ Strings must use singlequote.
     79 |      console.log("newVal:" + newVal + ";  old: "+ oldVal + "val: " + $scope.toogleBookedCars);
                                                          ^ Strings must use singlequote.
     79 |      console.log("newVal:" + newVal + ";  old: "+ oldVal + "val: " + $scope.toogleBookedCars);
                                                                            ^ Strings must use singlequote.
     97 |        console.log("free cars: ", freeCars);
                                          ^ Strings must use singlequote.
    123 |      for (var i = 0; i < car.bookings.length; i++) {
                                                         ^ Unexpected use of '++'.
    173 |      var car = _car
                             ^ Missing semicolon.
     68 |      var from = moment($scope.fromDate).hour($scope.fromTime.getHours()).minute($scope.fromTime.getMinutes());
                          ^ 'moment' is not defined.
     69 |      var to = moment($scope.toDate).hour($scope.toTime.getHours()).minute($scope.toTime.getMinutes());
                        ^ 'moment' is not defined.
   packages/cars/public/services/cars.js
     26 |      }
                ^ Missing semicolon.
     37 |        result.reason = "to is before from";
                                                    ^ Strings must use singlequote.
     39 |      };
                ^ Unnecessary semicolon.
     41 |      for (var i = 0; i < bookings.length; i++) {
                                                     ^ Unexpected use of '++'.
     53 |          result.reason = "Für diesen Zeitraum existiert bereits eine Buchung.";
                                                                                        ^ Strings must use singlequote.
     56 |      };
                ^ Unnecessary semicolon.
     32 |      var from = moment(booking.from);
                          ^ 'moment' is not defined.
     33 |      var to = moment(booking.to);
                        ^ 'moment' is not defined.
     42 |        var currentFrom = moment(bookings[i].from).subtract(1, 'seconds');
                                   ^ 'moment' is not defined.
     43 |        var currentTo = moment(bookings[i].to).add(1, 'seconds');
                                 ^ 'moment' is not defined.
   packages/cars/server/models/car.js
      8 |var moment = require('moment');
             ^ 'moment' is defined but never used.
   packages/cars/server/routes/cars.js
      7 |  console.log("USER111:",  req.user);
                                 ^ Strings must use singlequote.

>> 25 errors in 54 files
Warning: Task "jshint:all" failed. Used --force, continuing.

Running "csslint:src" (csslint) task
>> 6 files lint free.

Running "concurrent:tasks" (concurrent) task
Running "watch" task
Waiting...
Running "nodemon:dev" (nodemon) task
[nodemon] v1.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node --debug server.js`
debugger listening on port 5858
Mean app started on port 2602 (development)

mean -v && npm -v && node -v  
0.9.20
1.3.10
v0.10.25

BG
Andy

**Comment by DennisAhaus** [comment]
hi @ak0815 ,

this was only a test app and never intended to be used. Just for me to test usage of mean.io
